### ISSUE TITLE
No java class io.hstream.HStreamApiGrpc 

### ISSUE THREAD

**Issue by cb1980s** [hstreamdb/hstreamdb-java#4]
I created a new maven project in eclipse,and import hstreamdb-java files.It looks like good,but I found that there is no HStreamApiGrpc  java class after using protoc compiling hstream.proto,why?
    Any help could be appreicated.

**Comment by daleiz** [comment]
HStreamApiGrpc is a generated class and is not part of public api of this library. 
If you want to use this library, please see [doc](https://docs.hstream.io/develop/java-sdk/installation).
If you want to read source code of this library, you can clone the code and run ``gradle assemble``.

**Comment by cb1980s** [comment]
@daleiz,thank you for reply.I tried hstreamdb-java-0.1.0.jar(https://search.maven.org/artifact/io.hstream/hstreamdb-java/0.1.0/jar)  in java code,but class Consumer cann't be established.See the following code:
	Consumer consumer = client.newConsumer()
		        .subscription(TEST_SUBSCRIPTION)
		        .stream(TEST_STREAM)
		        .maxPollRecords(100)
		        .pollTimeoutMs(1000)
		        .build();
  eclipse report errors below:
       Caused by: io.grpc.StatusRuntimeException: INTERNAL: Subscription ID can not be found
	at io.grpc.Status.asRuntimeException(Status.java:534)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

   So,I think maybe it is necessary that recompile source code to generate new jar file.Does HStreamApiGrpc class generate from hstream.proto?I tried ,but no HStreamApiGrpc class.

**Comment by cb1980s** [comment]
In 'main' branch ,class ClientImpl has no method named 'createSubscrition'.

**Comment by daleiz** [comment]
@cb1980s I wrote an [example](https://github.com/daleiz/hstreamdb-java-example) and you can try it.
If you encounter any problems, feel free to give feedback.

**Comment by cb1980s** [comment]
@daleiz,thanks.I succeeded in recompiling hstreadb-java-0.2.0 project based on gradle.Now I will  pay more attention to the usage of hstreamdb-java.

**Comment by cb1980s** [comment]
Deal all,you should compile hstreamdb-java project using gradle if encountered the same issue.Thansk to @daleiz.
